/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/wolf-with-animations-f3769a474a714ebbbaca0d97f9b0a5a0
Title: Wolf with Animations
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import scene from '../assets/3d/wolf.glb'


export default function Wolf(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(scene);
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model"
                    rotation={[-Math.PI / 2, 0, -1.593]}
                    scale={1.977}
                >
                    <group
                        name="e4ef26d3d7a44d328db4b473b35c6be8fbx"
                        rotation={[Math.PI / 2, 0, 0]}
                    >
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="Object_4">
                                    <primitive object={nodes._rootJoint} />
                                    <skinnedMesh
                                        name="Object_7"
                                        geometry={nodes.Object_7.geometry}
                                        material={materials.fur__fella3_jpg_001}
                                        skeleton={nodes.Object_7.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_9"
                                        geometry={nodes.Object_9.geometry}
                                        material={materials.Material__wolf_col_tga}
                                        skeleton={nodes.Object_9.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_11"
                                        geometry={nodes.Object_11.geometry}
                                        material={materials.eyes}
                                        skeleton={nodes.Object_11.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_12"
                                        geometry={nodes.Object_12.geometry}
                                        material={materials.claws}
                                        skeleton={nodes.Object_12.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_13"
                                        geometry={nodes.Object_13.geometry}
                                        material={materials.teeth__nor2_tga}
                                        skeleton={nodes.Object_13.skeleton}
                                    />
                                    <group
                                        name="Object_6"
                                        position={[0, 0.002, 0]}
                                        rotation={[-Math.PI / 2, 0, 0]}
                                    />
                                    <group
                                        name="Object_8"
                                        position={[0, 0.002, 0]}
                                        rotation={[-Math.PI / 2, 0, 0]}
                                    />
                                    <group
                                        name="Object_10"
                                        position={[0, 0.002, 0]}
                                        rotation={[-Math.PI / 2, 0, 0]}
                                    />
                                    <group
                                        name="Plane"
                                        position={[0, -0.348, 0]}
                                        rotation={[-Math.PI / 2, 0, 0]}
                                    >
                                        <mesh
                                            name="Plane_unnamed_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Plane_unnamed_0.geometry}
                                            material={materials.unnamed}
                                        />
                                    </group>
                                    <group name="Wolf2" position={[0, 0, 0.002]} />
                                    <group name="Wolf1" position={[0, 0, 0.002]} />
                                    <group name="Wolf3" position={[0, 0, 0.002]} />
                                    <group
                                        name="Hemi"
                                        position={[-0.85, 1.001, 0.915]}
                                        rotation={[0.751, 0.1, 0.083]}
                                    >
                                        <group name="Object_68" rotation={[Math.PI / 2, 0, 0]}>
                                            <group name="Object_69" />
                                        </group>
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/wolf.glb");
